// BUGS
export const GET_BUGS = 'GET_BUGS';
export const ADD_BUGS = 'ADD_BUGS';
export const DELETE_BUGS = 'DELETE_BUGS';
export const UPDATE_BUGS = 'UPDATE_BUGS';
export const BUG_ERROR = 'BUG_ERROR';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAT_CURRENT';
export const FILTER_BUGS = 'FILTER_BUGS';
export const CLEAR_BUGS_FILTER = 'CLEAR_BUGS_FILTER';
// USERS
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
// ARTICLES
export const GET_ARTICLES = 'GET_ARTICLES';
export const ADD_ARTICLES = 'ADD_ARTICLES';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const ARTICLES_ERROR = 'ARTICLES_ERROR';
export const SET_CURRENT_ARTICLE = 'SET_CURRENT_ARTICLE';
export const CLEAR_CURRENT_ARTICLE = 'CLEAR_CURRENT_ARTICLE';
export const FILTER_ARTICLES = 'FILTER_ARTICLES';
export const CLEAR_ARTICLES_FILTER = 'CLEAR_ARTICLES_FILTER';
// ALERTS
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
